### ISSUE TITLE
CCGheart bug

### ISSUE THREAD

**Issue by samamckenzie** [cortex-lab/groundTruth#2]
It looks like there is some precision error on the CCG heart function that results in uneven binning with small bins (e.g. 0.4ms).  I have the same issue when I use your compiled mex file and when I compile my own. It has to do with the floor function, and perhaps the entire math.h library, but beyond this I have no other insights.

**Comment by nsteinme** [comment]
Have you tried using it with time in units of samples rather than seconds?
So a 0.4ms bin would be a bin size of maybe 12 samples? I think it is
designed to be used that way. Kenneth wrote this - or at least I got it
from him - we can ask him for more details if that answer doesn't help.

Nick

**Comment by samamckenzie** [comment]
Yes and that works. Also, if using a bin that is an even fraction of the
sampling rate and adding machine level precision noise works too.

Thank you for getting back
