### ISSUE TITLE
missing readWaveformsFromDat.m

### ISSUE THREAD

**Issue by fish** [cortex-lab/groundTruth#3]
The function `readWaveformsFromDat` is called on [line 145 of compareClustering.m](https://github.com/cortex-lab/groundTruth/blob/master/evaluation/compareClustering.m#L145), but the function is not provided. Its purpose can be inferred, but is there any chance the repo could be updated to include it?

Thanks!!

**Comment by nsteinme** [comment]
done, sorry about that -
